#!/bin/bash
### This job file is meant to spawn an MPI-CUDA job over several GPUs, possibly on different nodes. The idea is to parse the output of qstat to know which logical "cores" have been attached to the job, and to use the numbers provided as device numbers. This script is compatible with the 1-GPU script written earlier (jobseq), that is to say that no GPU will be oversubscribed if both scripts are used simultaneously.
#PBS -A test
#PBS -l nodes=1:ppn=1

cd /home/frederic/explomig/fargo3d

# You may choose whatever 'device file' you want, but it must be readable by all processes (hence it must not be written to /state/partition1), and it is a good idea to link it to the JOBID in order not to interfere with the device file of another job. The following two lines should simply be cut and pasted in any GPU job batch file.
DEVFILE=$HOME/.gpu_$PBS_JOBID

sigmaslope=$(echo "($PBS_ARRAYID -11) * 0.2" | bc -l)


qstat -f -1 $PBS_JOBID | grep exec_host | tr "=" "\n" | tail -n 1|tr "+" "\n" | tr -d " " | sed -e 's|/|.local/|'> $DEVFILE

#In the above line, we append ".local" to the host names, since the 'gethostname' function of C yields this suffix (we use this function in the early device selection of FARGO3D).

#Note two important points below:
#- The use of --bind-to none (mandatory even for CPU jobs)
#- The use of the option +D $DEVFILE of fargo3d
mpirun --bind-to none -hostfile $PBS_NODEFILE ./fargo3d +D $DEVFILE -o "nu 1e-7 sigmaslope $sigmaslope PlanetConfig planets/neptune.cfg nx=512 ny=256 ymin=0.5 ymax=1.5 ntot=1001 ninterm=1000 OutputDir:/state/partition1/frederic/explomig/set6/run" -# $PBS_ARRAYID setups/fargo/fargo.par
